
export const CLIENT_CREATE_STARTED = 'CLIENT_CREATE_STARTED'
export const CLIENT_CREATE_SUCCESS = 'CLIENT_CREATE_SUCCESS'
export const CLIENT_CREATE_FAIL = 'CLIENT_CREATE_FAIL'
export const LOAD_CLIENT_SUCCESS = 'LOAD_CLIENT_SUCCESS'